In [91]:
import numpy as np
import pandas as pd

df = pd.read_csv("supermarket_sales-Sheet1.csv")

In [92]:
# a)
Yangon_city_data = df[df["City"] == "Yangon"]
Yangon_city_data

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,886-18-2897,A,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,19:06,Credit card,282.80,4.761905,14.1400,4.5
992,745-74-0715,A,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,20:46,Ewallet,116.06,4.761905,5.8030,8.8
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

In [93]:
# # b) Misread thought to only keep ones !(between 4 and 9.9)
# y1 = Yangon_city_data[Yangon_city_data["Rating"] <= 4]
# y2 = Yangon_city_data[9.9 <= Yangon_city_data["Rating"]]

# # display(y1, y2)

# Yangon_city_data = pd.DataFrame() # reset data
# # display(Yangon_city_data)
# Yangon_city_data = pd.concat([Yangon_city_data, y1, y2])
# display(Yangon_city_data)

In [94]:
# b)
display(Yangon_city_data.describe())
Yangon_city_data.drop(Yangon_city_data[Yangon_city_data["Rating"] <= 4].index, inplace=True)
Yangon_city_data.drop(Yangon_city_data[9.9 <= Yangon_city_data["Rating"]].index, inplace=True)
display(Yangon_city_data.describe())

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,340.000000,340.000000,340.000000,340.000000,340.000000,340.000000,340.000000,340.000000
mean,54.780853,5.467647,14.874001,312.354031,297.480029,4.761905,14.874001,7.027059
std,26.132127,2.859876,11.030477,231.640025,220.609547,0.000000,11.030477,1.731345
min,10.080000,1.000000,0.604500,12.694500,12.090000,4.761905,0.604500,4.000000
25%,32.250000,3.000000,6.547125,137.489625,130.942500,4.761905,6.547125,5.600000
50%,53.235000,5.000000,11.468000,240.828000,229.360000,4.761905,11.468000,7.100000
75%,75.095000,8.000000,21.873375,459.340875,437.467500,4.761905,21.873375,8.500000
max,99.830000,10.000000,49.490000,1039.290000,989.800000,4.761905,49.490000,10.000000

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000
mean,54.711364,5.472727,14.874597,312.366536,297.491939,4.761905,14.874597,6.975455
std,26.225542,2.866988,11.078695,232.652602,221.573907,0.000000,11.078695,1.681611
min,10.080000,1.000000,0.604500,12.694500,12.090000,4.761905,0.604500,4.100000
25%,30.970000,3.000000,6.486375,136.213875,129.727500,4.761905,6.486375,5.600000
50%,53.235000,5.000000,11.468000,240.828000,229.360000,4.761905,11.468000,7.000000
75%,75.165000,8.000000,21.827625,458.380125,436.552500,4.761905,21.827625,8.400000
max,99.830000,10.000000,49.490000,1039.290000,989.800000,4.761905,49.490000,9.800000

In [95]:
# c)
Yangon_city_data["New_total"] = Yangon_city_data["Unit price"]*Yangon_city_data["Quantity"] + Yangon_city_data["Tax 5%"]
display(Yangon_city_data)
Yangon_city_data.pivot_table(index=["Invoice ID"], values=["Total", "New_total"])

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,New_total
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,548.9715
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,340.5255
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,489.0480
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,634.3785
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8,433.6920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,886-18-2897,A,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,19:06,Credit card,282.80,4.761905,14.1400,4.5,296.9400
992,745-74-0715,A,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,20:46,Ewallet,116.06,4.761905,5.8030,8.8,121.8630
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7,33.4320
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1,69.1110
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6,649.2990

             New_total     Total
Invoice ID
101-17-6199   336.5565  336.5565
105-10-6182    45.1080   45.1080
105-31-1824   510.9720  510.9720
106-35-6779    93.1140   93.1140
123-19-1176   489.0480  489.0480
...                ...       ...
886-54-6089    72.0090   72.0090
888-02-0338   247.8735  247.8735
892-05-6689   148.6800  148.6800
896-34-0956    22.3860   22.3860
898-04-2717   721.9800  721.9800

[330 rows x 2 columns]

In [96]:
Yangon_city_data["Difference"] = round(Yangon_city_data["Total"] - Yangon_city_data["New_total"])
Yangon_city_data.pivot_table(index=["Invoice ID"], values=["Total", "New_total", "Difference"])

             Difference  New_total     Total
Invoice ID
101-17-6199         0.0   336.5565  336.5565
105-10-6182         0.0    45.1080   45.1080
105-31-1824         0.0   510.9720  510.9720
106-35-6779         0.0    93.1140   93.1140
123-19-1176         0.0   489.0480  489.0480
...                 ...        ...       ...
886-54-6089         0.0    72.0090   72.0090
888-02-0338         0.0   247.8735  247.8735
892-05-6689         0.0   148.6800  148.6800
896-34-0956         0.0    22.3860   22.3860
898-04-2717         0.0   721.9800  721.9800

[330 rows x 3 columns]

In [97]:
# # d) so close to working.
# def member_or_not(x):
#     if x == "Member":
#         return 0.9 
#     else:
#         return 1

# Yangon_city_data["Final_price"] = Yangon_city_data["Total"]*(member_or_not(Yangon_city_data["Customer type"]))
# Yangon_city_data.pivot_table(index=["Invoice ID"], values=["Total", "Final_price"])

In [100]:
# d)
Yangon_city_data["Final_price"] = Yangon_city_data.apply(lambda i: i["Total"]*0.9 if i["Customer type"] == "Member" else i["Total"], axis=1)
Yangon_city_data.pivot_table(index=["Invoice ID"], values=["Total", "Final_price"])

             Final_price     Total
Invoice ID
101-17-6199     336.5565  336.5565
105-10-6182      40.5972   45.1080
105-31-1824     459.8748  510.9720
106-35-6779      83.8026   93.1140
123-19-1176     440.1432  489.0480
...                  ...       ...
886-54-6089      72.0090   72.0090
888-02-0338     247.8735  247.8735
892-05-6689     148.6800  148.6800
896-34-0956      22.3860   22.3860
898-04-2717     721.9800  721.9800

[330 rows x 2 columns]